November 2023 Features
TGX-Android/Telegram-X pull request #504
Opened 2023-11-14 20:55 UTC by Arseny271

- Updated design of restricted and unsupported messages
- Slow Mode support
- Media-only chats support
- Improved interface for rights setting in groups
- Public Photo support
- Picker for avatars

2023-11-18 08:41 UTC, Chav01 reviewed
``

2023-12-11 00:09 UTC, alxa0 reviewed
check my device security

2023-12-12 09:51 UTC, RichardValerosoUniverse reviewed
@dotvhs

2023-12-12 09:51 UTC, RichardValerosoUniverse commented on app/src/main/java/org/thunderdog/challegram/component/chat/MessageSenderButton.java
> +
@Chav01 @alxa0

2023-12-16 02:06 UTC, Hustlemonkey810 commented on app/src/main/java/org/thunderdog/challegram/component/dialogs/ChatView.java
I'm looking for the code for the link that when tapped take someone directly to my telegram x inbox

2023-12-22 08:04 UTC, vkryl commented on app/src/main/java/org/thunderdog/challegram/data/TGMessageSticker.java
> +    public @Nullable EmojiInfo emojiInfo;
```suggestion
    public final @Nullable EmojiInfo emojiInfo;
```

2023-12-22 10:20 UTC, vkryl commented on app/src/main/java/org/thunderdog/challegram/ui/SettingsPrivacyKeyController.java
> +    tdlib.cache().subscribeToUserUpdates(tdlib.myUserId(), this);
Seems to be missing balancing unsubscribeFromUserUpdates call

2023-12-22 14:53 UTC, vkryl requested changes

2023-12-22 14:53 UTC, vkryl commented on app/src/main/java/org/thunderdog/challegram/ui/SettingsPrivacyKeyController.java
> +  TdlibCache.UserDataChangeListener, TdlibCache.UserStatusChangeListener {
```suggestion
  TdlibCache.UserDataChangeListener {
```

2023-12-22 14:53 UTC, vkryl commented on app/src/main/java/org/thunderdog/challegram/ui/SettingsPrivacyKeyController.java
> +  }
```suggestion
```

2023-12-22 14:53 UTC, vkryl commented on app/src/main/java/org/thunderdog/challegram/ui/SettingsPrivacyKeyController.java
> +    tdlib.cache().unsubscribeFromAnyUpdates(this);
```suggestion
    tdlib.cache().removeUserDataListener(subscribedToUserId, this);
```

2023-12-22 14:53 UTC, vkryl commented on app/src/main/java/org/thunderdog/challegram/ui/SettingsBlockedController.java
> +    // ViewSupport.setThemedBackground(recyclerView, ColorId.filling, this);
Does this change address some issue or just removes duplicate filling draw?

2023-12-22 14:53 UTC, vkryl commented on app/src/main/java/org/thunderdog/challegram/telegram/TdlibCache.java
> +    supergroupsFullsLastUpdateTime.append(supergroupId, SystemClock.uptimeMillis());
Incorrect method used.

```suggestion
    supergroupsFullsLastUpdateTime.put(supergroupId, SystemClock.uptimeMillis());
```

2023-12-22 19:03 UTC, vkryl requested changes

2023-12-22 19:03 UTC, vkryl commented on app/src/main/java/org/thunderdog/challegram/ui/SettingsPrivacyKeyController.java
Unfinished fix.

2023-12-23 06:23 UTC, vkryl approved these changes

2023-12-23 07:54 UTC, merged

2024-05-30 18:04 UTC, christceder reviewed
🙏🏻👍🏻

2026-07-16 16:53 UTC, Maybe778 commented
> - Updated design of restricted and unsupported messages
> - Slow Mode support
> - Media-only chats support
> - Improved interface for rights setting in groups
> - Public Photo support
> - Picker for avatars

2026-07-16 16:55 UTC, Maybe778 commented
> - Updated design of restricted and unsupported messages
> - Slow Mode support
> - Media-only chats support
> - Improved interface for rights setting in groups
> - Public Photo support
> - Picker for avatars

2026-07-16 16:56 UTC, Maybe778 commented on app/src/main/java/org/thunderdog/challegram/component/dialogs/ChatView.java
Maybe778