Clear calls history in one click
TGX-Android/Telegram-X pull request #527
Opened 2024-01-07 11:57 UTC by null-nick

2024-01-07 20:30 UTC, vkryl commented
I am not sure if it is WIP or not, but it clearly does not match description of #526. It just clears call log without any confirmation after holding `Calls` in drawer.

2024-01-08 17:10 UTC, null-nick commented
> I am not sure if it is WIP or not, but it clearly does not match description of #526. It just clears call log without any confirmation after holding `Calls` in drawer.

can you re-open the pr ?

2025-03-13 00:07 UTC, null-nick commented
Ok Done

2026-07-12 23:50 UTC, Alikahrizzi reviewed
86e2fbc1c2193e9d40d3f49b902085f753370960

2026-08-25 09:19 UTC, vkryl requested changes

2026-08-25 09:19 UTC, vkryl commented on app/src/main/java/org/thunderdog/challegram/telegram/Tdlib.java
> +    send(new TdApi.DeleteAllCallMessages(revoke), okHandler(after));
```suggestion
    send(new TdApi.DeleteAllCallMessages(revoke), typedOkHandler(after));
```

2026-08-25 09:19 UTC, vkryl commented on app/src/main/java/org/thunderdog/challegram/telegram/TdlibUi.java
> +    tdlib.send(new TdApi.SearchCallMessages("", 1, false), (result, error) -> {
```suggestion
    tdlib.send(new TdApi.SearchCallMessages(null, 1, false), (result, error) -> {
```

2026-08-25 09:19 UTC, vkryl commented on app/src/main/res/values/strings.xml
> +  <string name="AreYouSureClearCalls">Do you want to delete all recent calls?</string>
```suggestion
  <string name="DeleteCallHistoryConfirm">**Warning!**\n\nDo you want to delete **entire** call history? This will delete all associated call messages in corresponding chats.\n\nThis action cannot be undone.</string>
```

2026-08-25 09:19 UTC, vkryl commented on app/src/main/res/values/strings.xml
> +  <string name="ClearRecentCalls">Clear recent calls</string>
```suggestion
  <string name="DeleteCallHistory">Delete call history</string>
```

2026-08-25 09:19 UTC, vkryl commented on app/src/main/res/values/strings.xml
> +  <string name="DeleteCallsForEveryone">Delete for everyone</string>
```suggestion
  <string name="DeleteCallHistoryForEveryone">Delete for everyone</string>
```

2026-08-25 09:19 UTC, vkryl commented on app/src/main/java/org/thunderdog/challegram/telegram/TdlibUi.java
> +            new ListItem(ListItem.TYPE_CHECKBOX_OPTION, R.id.btn_deleteAll, 0, R.string.DeleteCallsForEveryone, false)
```suggestion
            new ListItem(ListItem.TYPE_CHECKBOX_OPTION, R.id.btn_deleteAll, 0, R.string.DeleteCallHistoryForEveryone, false)
```

2026-08-25 09:19 UTC, vkryl commented on app/src/main/java/org/thunderdog/challegram/telegram/TdlibUi.java
> +          .addHeaderItem(Lang.getString(R.string.AreYouSureClearCalls))
```suggestion
          .addHeaderItem(Lang.getMarkdownString(context, R.string.DeleteCallHistoryConfirm))
```

2026-08-25 09:19 UTC, vkryl commented on app/src/main/java/org/thunderdog/challegram/ui/CallListController.java
> +      showMore(new int[] {R.id.btn_clear_recent_calls}, new String[] {Lang.getString(R.string.ClearRecentCalls)});
```suggestion
      showMore(new int[] {R.id.more_btn_delete}, new String[] {Lang.getString(R.string.DeleteCallHistory)});
```

2026-08-25 09:19 UTC, vkryl commented on app/src/main/java/org/thunderdog/challegram/ui/CallListController.java
> +    if (id == R.id.btn_clear_recent_calls) {
```suggestion
    if (id == R.id.more_btn_delete) {
```

2026-08-25 09:19 UTC, vkryl commented on app/src/main/res/values/ids.xml
> +
```suggestion
```

2026-08-25 09:19 UTC, vkryl commented on app/src/main/res/values/ids.xml
Can be untracked, just reuse more_btn_delete.

2026-08-25 20:40 UTC, vkryl commented on app/src/main/res/values/ids.xml
git checkout main -- ids.xml

2026-08-25 20:42 UTC, vkryl reviewed
ids.xml can be left unchanged

2026-08-25 20:42 UTC, vkryl commented on app/src/main/res/values/ids.xml
> +
```suggestion
```

2026-08-25 20:50 UTC, vkryl approved these changes

2026-08-29 08:01 UTC, merged

2026-08-29 18:13 UTC, zarmamedia-227 commented
Zarma wallet